Master Volume Option
elishacloud/Silent-Hill-2-Enhancements pull request #797
Opened 2023-06-14 11:55 UTC by mercury501

Hi there!

This PR contains the following:
Master volume level handling and storage (from @elishacloud)
Recreating the "slider" to be identical to the other existing ones
Handling input, changed settings and changes in resolution

Cheers!

2023-06-14 12:50 UTC, Polymega commented
![l4lWo7l](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/73ac337e-15f9-4a76-801a-255db2929329)

2023-06-14 17:45 UTC, elishacloud requested changes
Great job!  Just one comment.

2023-06-14 18:01 UTC, mercury501 commented on dllmain.cpp
> +		PatchMasterVolumeSlider();
Sure thing @elishacloud, makes sense!

2023-06-14 18:04 UTC, mercury501 commented
Oh and te EnableMasterVolume setting would need translating in all languages other than english and italian!

2023-06-14 18:16 UTC, Polymega commented
> Oh and the EnableMasterVolume setting would need translating in all languages other than english and italian!

@lucazandrade @IlDucci 
May I ask you two to provide translations for the following?

@lucazandrade (PTBR)
https://github.com/mercury501/Silent-Hill-2-Enhancements/blob/MasterVolumeSlider/Launcher/config_br.xml#L357-L358

@IlDucci (Spanish)
https://github.com/mercury501/Silent-Hill-2-Enhancements/blob/MasterVolumeSlider/Launcher/config_es.xml#L357-L358

2023-06-14 18:46 UTC, lucazandrade commented
> > Oh and the EnableMasterVolume setting would need translating in all languages other than english and italian!
> 
> @lucazandrade @IlDucci May I ask you two to provide translations for the following?
> 
> @lucazandrade (PTBR) https://github.com/mercury501/Silent-Hill-2-Enhancements/blob/MasterVolumeSlider/Launcher/config_br.xml#L357-L358
> 
> @IlDucci (Spanish) https://github.com/mercury501/Silent-Hill-2-Enhancements/blob/MasterVolumeSlider/Launcher/config_es.xml#L357-L358

Done: https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/798/commits/636c2e4c7dcee6c5fc0be5886b1ceae343a68d81#diff-e7b51e253f4590bcc5cd4c5ef983ddeaf7d791e67e9dc84951eae5ccb1ad5b0f

Thanks for that, it's always a pleasure!!

2023-06-14 18:50 UTC, elishacloud approved these changes

2023-06-14 19:46 UTC, IlDucci commented
Done! https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/799

2023-06-15 21:54 UTC, merged

2023-06-15 21:54 UTC, elishacloud commented
Nice work!

2023-06-15 22:32 UTC, elishacloud commented
Here is the latest merged code with the translations.  Let me know if anything is missing.

New build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11763747/d3d8.zip)

2023-06-16 19:15 UTC, Polymega commented
Thanks, Elisha! I know this is likely beyond our control, but I wanted to point out that Windows wasn't liking this test build, for some reason:

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/717be978-5cfc-4f65-a857-7dc63308c576)
![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/7d6a15c6-d604-4d47-857c-a066b9b61560)

2023-06-16 19:56 UTC, elishacloud commented
Yeah, there is no easy way to completely prevent that.  That is another False Positive.  Once the file is out for a while it will stop detecting it.

2023-06-17 00:59 UTC, Polymega commented
@virake @IlDucci 
Looking ahead, as part of our next project update we'll be releasing a new "Master Volume" feature ([see here](https://www.youtube.com/watch?v=JEkH0E0rwUk)). This feature will utilize two new, custom text strings, which means these text strings would also need to be translated as part of your translation packs.

The text strings are:

```
Master Volume
Adjust master volume
```

At your convenience, would you please add the following lines to your respective `r_resource_*.res` files that's included in your translation pack?

![image](https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/d2e7aacc-abf7-412a-b1ff-210e516f4e4b)

This two new strings would be added to lines `28` and `29` in the `r_resource_*.res` file. 
_Make sure to keep the "\h" at the beginning of the text strings._

If you need to, you can grab your translation pack files from the project site: https://enhanced.townofsilenthill.com/SH2/languagepacks.htm

Thank you both

2023-06-18 09:03 UTC, IlDucci commented
Here's Castilian Spanish:
[SH2EE_LangPack_Castilian_Spanish_V1.0.4.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11780998/SH2EE_LangPack_Castilian_Spanish_V1.0.4.zip)

By the way, was the file name r_resource_X or r_menu_X? Was it changed?

2023-06-18 13:10 UTC, Polymega commented
Thanks, IlDucci!

> By the way, was the file name r_resource_X or r_menu_X? Was it changed?

I wasn't on my normal computer when I wrote that, so I was going off of memory and got it incorrect. It's still `r_menu_*`. I'll update my post on that. Thanks